# DOSee Docker compose to load an nginx webhost server
#
# Run: docker-compose up -d
# Access in a browser: http://localhost:5550
#
# Shell access: docker-compose exec web sh
# Reset containers: docker-compose rm
# Reset volumes: docker-compose down --volumes

version: "3.2"

services:
  web:
    labels:
      net.dosee.description: "DOSee - A MS-DOS emulator for the web"
    container_name: "dosee"
    # nginx stable is used due to its less frequent updates
    # alpine is a tiny linux distribution
    image: nginx:stable-alpine
    # expose nginx web port 80 as port 5550
    ports:
      - "5550:80"
    volumes:
      # bind your local cloned DOSee repo to nginx's html hosting path
      - type: bind
        source: ./build
        target: /usr/share/nginx/html
